apiVersion: v1
kind: Service
metadata:
  labels:
    app: queue
  name: queue
spec:
  selector:
    app: queue
  ports:
  - name: port-8100
    protocol: TCP
    port: 8100
    targetPort: 8101
  clusterIP: 10.244.0.32
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: queue-statefullset
  labels:
    app: queue
spec:
  replicas: 2
  selector:
    matchLabels:
      app: queue
  template:
    metadata:
      labels:
        app: queue
    spec:
      containers:
      - name: queue-container
        image: my_queue:v1
        command: ["python"]
        args: ["/root/queue.py", "8101"]
        ports:
        - containerPort: 8101

