apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker-deployment
  labels:
    app: worker
spec:
  replicas: 4
  selector:
    matchLabels:
      app: worker
  template:
    metadata:
      labels:
        app: worker
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: worker-container
        image: my_worker:v1
        command: ["python"]
        args: ["/root/worker.py", "queue1", "10.244.0.32:8100"]

